# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.settingsTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.settingsTabWidget.setGeometry(QtCore.QRect(10, 10, 351, 361))
        self.settingsTabWidget.setObjectName("settingsTabWidget")
        self.simpleSettingsTab = QtWidgets.QWidget()
        self.simpleSettingsTab.setObjectName("simpleSettingsTab")
        self.folderGroup = QtWidgets.QGroupBox(self.simpleSettingsTab)
        self.folderGroup.setGeometry(QtCore.QRect(10, 10, 331, 101))
        self.folderGroup.setObjectName("folderGroup")
        self.loadFolderLabel = QtWidgets.QLabel(self.folderGroup)
        self.loadFolderLabel.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.loadFolderLabel.setObjectName("loadFolderLabel")
        self.loadFolderEdit = QtWidgets.QLineEdit(self.folderGroup)
        self.loadFolderEdit.setEnabled(True)
        self.loadFolderEdit.setGeometry(QtCore.QRect(100, 30, 191, 22))
        self.loadFolderEdit.setReadOnly(True)
        self.loadFolderEdit.setObjectName("loadFolderEdit")
        self.loadFolderButton = QtWidgets.QToolButton(self.folderGroup)
        self.loadFolderButton.setGeometry(QtCore.QRect(300, 30, 23, 21))
        self.loadFolderButton.setObjectName("loadFolderButton")
        self.saveFolderLabel = QtWidgets.QLabel(self.folderGroup)
        self.saveFolderLabel.setGeometry(QtCore.QRect(10, 60, 91, 21))
        self.saveFolderLabel.setObjectName("saveFolderLabel")
        self.saveFolderEdit = QtWidgets.QLineEdit(self.folderGroup)
        self.saveFolderEdit.setEnabled(True)
        self.saveFolderEdit.setGeometry(QtCore.QRect(100, 60, 191, 22))
        self.saveFolderEdit.setReadOnly(True)
        self.saveFolderEdit.setObjectName("saveFolderEdit")
        self.saveFolderButton = QtWidgets.QToolButton(self.folderGroup)
        self.saveFolderButton.setGeometry(QtCore.QRect(300, 60, 23, 21))
        self.saveFolderButton.setObjectName("saveFolderButton")
        self.settingsTabWidget.addTab(self.simpleSettingsTab, "")
        self.advancedSettingsTab = QtWidgets.QWidget()
        self.advancedSettingsTab.setObjectName("advancedSettingsTab")
        self.settingsTabWidget.addTab(self.advancedSettingsTab, "")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(380, 10, 601, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.plotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.plotLayout.setContentsMargins(0, 0, 0, 0)
        self.plotLayout.setObjectName("plotLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.saveConfigAction = QtWidgets.QAction(MainWindow)
        self.saveConfigAction.setObjectName("saveConfigAction")
        self.loadConfigAction = QtWidgets.QAction(MainWindow)
        self.loadConfigAction.setObjectName("loadConfigAction")
        self.actionLight = QtWidgets.QAction(MainWindow)
        self.actionLight.setObjectName("actionLight")
        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setObjectName("actionDark")

        self.retranslateUi(MainWindow)
        self.settingsTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "POD Filter"))
        self.folderGroup.setTitle(_translate("MainWindow", "Folder Settings"))
        self.loadFolderLabel.setText(_translate("MainWindow", "Load Folder"))
        self.loadFolderButton.setText(_translate("MainWindow", "..."))
        self.saveFolderLabel.setText(_translate("MainWindow", "Save Folder"))
        self.saveFolderButton.setText(_translate("MainWindow", "..."))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.simpleSettingsTab), _translate("MainWindow", "Simple Settings"))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.advancedSettingsTab), _translate("MainWindow", "Advanced Settings"))
        self.saveConfigAction.setText(_translate("MainWindow", "Save Configuration"))
        self.saveConfigAction.setShortcut(_translate("MainWindow", "Ctrl+Alt+S"))
        self.loadConfigAction.setText(_translate("MainWindow", "Load Configuration"))
        self.actionLight.setText(_translate("MainWindow", "Light"))
        self.actionDark.setText(_translate("MainWindow", "Dark"))
